packages:
  - apps/*
  - packages/*

allowBuilds:
  "@scarf/scarf": set this to true or false
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true
  ssh2: false

confirmModulesPurge: false

catalog:
  "@nestjs/common": latest
  "@nestjs/core": latest
  "@nestjs/platform-express": latest
  "@nestjs/swagger": latest
  "@testcontainers/postgresql": latest
  "@vscode/tree-sitter-wasm": 0.3.1
  bullmq: latest
  ioredis: 5.10.1
  kysely: latest
  next: latest
  pg: latest
  react: latest
  react-dom: latest
  reflect-metadata: latest
  rxjs: latest
  testcontainers: latest
  tree-sitter-wasms: 0.1.13
  typescript: 6.0.3
  web-tree-sitter: 0.26.11
  web-tree-sitter-legacy: npm:web-tree-sitter@0.25.10
  zod: latest
