<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>demo</groupId>
  <artifactId>vertx-notifications</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-web</artifactId>
      <version>4.5.8</version>
    </dependency>
  </dependencies>
</project>
